package com.cqjtu.sc.orderservice.db.domain;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class AllOrderDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_order_detail.order_detail_id
     *
     * @mbg.generated
     */
    private Integer orderDetailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_order_detail.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_order_detail.goods_id
     *
     * @mbg.generated
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_order_detail.order_id
     *
     * @mbg.generated
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_order_detail.all_order_id
     *
     * @mbg.generated
     */
    private Integer allOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_order_detail.quantity
     *
     * @mbg.generated
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_order_detail.order_detail_number
     *
     * @mbg.generated
     */
    private String orderDetailNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_order_detail.goodsStatus
     *
     * @mbg.generated
     */
    private Integer goodsstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_order_detail.ratio
     *
     * @mbg.generated
     */
    private Integer ratio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_order_detail.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_order_detail.ship_channel
     *
     * @mbg.generated
     */
    private String shipChannel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_order_detail.ship_sn
     *
     * @mbg.generated
     */
    private String shipSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_order_detail.ship_time
     *
     * @mbg.generated
     */
    private LocalDateTime shipTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_order_detail.order_detail_id
     *
     * @return the value of all_order_detail.order_detail_id
     *
     * @mbg.generated
     */
    public Integer getOrderDetailId() {
        return orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_order_detail.order_detail_id
     *
     * @param orderDetailId the value for all_order_detail.order_detail_id
     *
     * @mbg.generated
     */
    public void setOrderDetailId(Integer orderDetailId) {
        this.orderDetailId = orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_order_detail.id
     *
     * @return the value of all_order_detail.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_order_detail.id
     *
     * @param id the value for all_order_detail.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_order_detail.goods_id
     *
     * @return the value of all_order_detail.goods_id
     *
     * @mbg.generated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_order_detail.goods_id
     *
     * @param goodsId the value for all_order_detail.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_order_detail.order_id
     *
     * @return the value of all_order_detail.order_id
     *
     * @mbg.generated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_order_detail.order_id
     *
     * @param orderId the value for all_order_detail.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_order_detail.all_order_id
     *
     * @return the value of all_order_detail.all_order_id
     *
     * @mbg.generated
     */
    public Integer getAllOrderId() {
        return allOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_order_detail.all_order_id
     *
     * @param allOrderId the value for all_order_detail.all_order_id
     *
     * @mbg.generated
     */
    public void setAllOrderId(Integer allOrderId) {
        this.allOrderId = allOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_order_detail.quantity
     *
     * @return the value of all_order_detail.quantity
     *
     * @mbg.generated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_order_detail.quantity
     *
     * @param quantity the value for all_order_detail.quantity
     *
     * @mbg.generated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_order_detail.order_detail_number
     *
     * @return the value of all_order_detail.order_detail_number
     *
     * @mbg.generated
     */
    public String getOrderDetailNumber() {
        return orderDetailNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_order_detail.order_detail_number
     *
     * @param orderDetailNumber the value for all_order_detail.order_detail_number
     *
     * @mbg.generated
     */
    public void setOrderDetailNumber(String orderDetailNumber) {
        this.orderDetailNumber = orderDetailNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_order_detail.goodsStatus
     *
     * @return the value of all_order_detail.goodsStatus
     *
     * @mbg.generated
     */
    public Integer getGoodsstatus() {
        return goodsstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_order_detail.goodsStatus
     *
     * @param goodsstatus the value for all_order_detail.goodsStatus
     *
     * @mbg.generated
     */
    public void setGoodsstatus(Integer goodsstatus) {
        this.goodsstatus = goodsstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_order_detail.ratio
     *
     * @return the value of all_order_detail.ratio
     *
     * @mbg.generated
     */
    public Integer getRatio() {
        return ratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_order_detail.ratio
     *
     * @param ratio the value for all_order_detail.ratio
     *
     * @mbg.generated
     */
    public void setRatio(Integer ratio) {
        this.ratio = ratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_order_detail.amount
     *
     * @return the value of all_order_detail.amount
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_order_detail.amount
     *
     * @param amount the value for all_order_detail.amount
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_order_detail.ship_channel
     *
     * @return the value of all_order_detail.ship_channel
     *
     * @mbg.generated
     */
    public String getShipChannel() {
        return shipChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_order_detail.ship_channel
     *
     * @param shipChannel the value for all_order_detail.ship_channel
     *
     * @mbg.generated
     */
    public void setShipChannel(String shipChannel) {
        this.shipChannel = shipChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_order_detail.ship_sn
     *
     * @return the value of all_order_detail.ship_sn
     *
     * @mbg.generated
     */
    public String getShipSn() {
        return shipSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_order_detail.ship_sn
     *
     * @param shipSn the value for all_order_detail.ship_sn
     *
     * @mbg.generated
     */
    public void setShipSn(String shipSn) {
        this.shipSn = shipSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_order_detail.ship_time
     *
     * @return the value of all_order_detail.ship_time
     *
     * @mbg.generated
     */
    public LocalDateTime getShipTime() {
        return shipTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_order_detail.ship_time
     *
     * @param shipTime the value for all_order_detail.ship_time
     *
     * @mbg.generated
     */
    public void setShipTime(LocalDateTime shipTime) {
        this.shipTime = shipTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_order_detail
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderDetailId=").append(orderDetailId);
        sb.append(", id=").append(id);
        sb.append(", goodsId=").append(goodsId);
        sb.append(", orderId=").append(orderId);
        sb.append(", allOrderId=").append(allOrderId);
        sb.append(", quantity=").append(quantity);
        sb.append(", orderDetailNumber=").append(orderDetailNumber);
        sb.append(", goodsstatus=").append(goodsstatus);
        sb.append(", ratio=").append(ratio);
        sb.append(", amount=").append(amount);
        sb.append(", shipChannel=").append(shipChannel);
        sb.append(", shipSn=").append(shipSn);
        sb.append(", shipTime=").append(shipTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_order_detail
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AllOrderDetail other = (AllOrderDetail) that;
        return (this.getOrderDetailId() == null ? other.getOrderDetailId() == null : this.getOrderDetailId().equals(other.getOrderDetailId()))
            && (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getGoodsId() == null ? other.getGoodsId() == null : this.getGoodsId().equals(other.getGoodsId()))
            && (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()))
            && (this.getAllOrderId() == null ? other.getAllOrderId() == null : this.getAllOrderId().equals(other.getAllOrderId()))
            && (this.getQuantity() == null ? other.getQuantity() == null : this.getQuantity().equals(other.getQuantity()))
            && (this.getOrderDetailNumber() == null ? other.getOrderDetailNumber() == null : this.getOrderDetailNumber().equals(other.getOrderDetailNumber()))
            && (this.getGoodsstatus() == null ? other.getGoodsstatus() == null : this.getGoodsstatus().equals(other.getGoodsstatus()))
            && (this.getRatio() == null ? other.getRatio() == null : this.getRatio().equals(other.getRatio()))
            && (this.getAmount() == null ? other.getAmount() == null : this.getAmount().equals(other.getAmount()))
            && (this.getShipChannel() == null ? other.getShipChannel() == null : this.getShipChannel().equals(other.getShipChannel()))
            && (this.getShipSn() == null ? other.getShipSn() == null : this.getShipSn().equals(other.getShipSn()))
            && (this.getShipTime() == null ? other.getShipTime() == null : this.getShipTime().equals(other.getShipTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_order_detail
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOrderDetailId() == null) ? 0 : getOrderDetailId().hashCode());
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getGoodsId() == null) ? 0 : getGoodsId().hashCode());
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        result = prime * result + ((getAllOrderId() == null) ? 0 : getAllOrderId().hashCode());
        result = prime * result + ((getQuantity() == null) ? 0 : getQuantity().hashCode());
        result = prime * result + ((getOrderDetailNumber() == null) ? 0 : getOrderDetailNumber().hashCode());
        result = prime * result + ((getGoodsstatus() == null) ? 0 : getGoodsstatus().hashCode());
        result = prime * result + ((getRatio() == null) ? 0 : getRatio().hashCode());
        result = prime * result + ((getAmount() == null) ? 0 : getAmount().hashCode());
        result = prime * result + ((getShipChannel() == null) ? 0 : getShipChannel().hashCode());
        result = prime * result + ((getShipSn() == null) ? 0 : getShipSn().hashCode());
        result = prime * result + ((getShipTime() == null) ? 0 : getShipTime().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table all_order_detail
     *
     * @mbg.generated
     */
    public enum Column {
        orderDetailId("order_detail_id", "orderDetailId", "INTEGER", false),
        id("id", "id", "INTEGER", false),
        goodsId("goods_id", "goodsId", "INTEGER", false),
        orderId("order_id", "orderId", "INTEGER", false),
        allOrderId("all_order_id", "allOrderId", "INTEGER", false),
        quantity("quantity", "quantity", "INTEGER", false),
        orderDetailNumber("order_detail_number", "orderDetailNumber", "VARCHAR", false),
        goodsstatus("goodsStatus", "goodsstatus", "INTEGER", false),
        ratio("ratio", "ratio", "INTEGER", false),
        amount("amount", "amount", "DECIMAL", false),
        shipChannel("ship_channel", "shipChannel", "VARCHAR", false),
        shipSn("ship_sn", "shipSn", "VARCHAR", false),
        shipTime("ship_time", "shipTime", "TIMESTAMP", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table all_order_detail
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table all_order_detail
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table all_order_detail
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table all_order_detail
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table all_order_detail
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table all_order_detail
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_order_detail
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_order_detail
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_order_detail
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_order_detail
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_order_detail
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_order_detail
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_order_detail
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_order_detail
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_order_detail
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_order_detail
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}