package com.cqjtu.sc.orderservice.db.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;

public class Brokerage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brokerage.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brokerage.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brokerage.generated_brokerage
     *
     * @mbg.generated
     */
    private BigDecimal generatedBrokerage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brokerage.gained_brokerage
     *
     * @mbg.generated
     */
    private BigDecimal gainedBrokerage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brokerage.id
     *
     * @return the value of brokerage.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brokerage.id
     *
     * @param id the value for brokerage.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brokerage.user_id
     *
     * @return the value of brokerage.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brokerage.user_id
     *
     * @param userId the value for brokerage.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brokerage.generated_brokerage
     *
     * @return the value of brokerage.generated_brokerage
     *
     * @mbg.generated
     */
    public BigDecimal getGeneratedBrokerage() {
        return generatedBrokerage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brokerage.generated_brokerage
     *
     * @param generatedBrokerage the value for brokerage.generated_brokerage
     *
     * @mbg.generated
     */
    public void setGeneratedBrokerage(BigDecimal generatedBrokerage) {
        this.generatedBrokerage = generatedBrokerage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brokerage.gained_brokerage
     *
     * @return the value of brokerage.gained_brokerage
     *
     * @mbg.generated
     */
    public BigDecimal getGainedBrokerage() {
        return gainedBrokerage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brokerage.gained_brokerage
     *
     * @param gainedBrokerage the value for brokerage.gained_brokerage
     *
     * @mbg.generated
     */
    public void setGainedBrokerage(BigDecimal gainedBrokerage) {
        this.gainedBrokerage = gainedBrokerage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brokerage
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", generatedBrokerage=").append(generatedBrokerage);
        sb.append(", gainedBrokerage=").append(gainedBrokerage);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brokerage
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Brokerage other = (Brokerage) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getGeneratedBrokerage() == null ? other.getGeneratedBrokerage() == null : this.getGeneratedBrokerage().equals(other.getGeneratedBrokerage()))
            && (this.getGainedBrokerage() == null ? other.getGainedBrokerage() == null : this.getGainedBrokerage().equals(other.getGainedBrokerage()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brokerage
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getGeneratedBrokerage() == null) ? 0 : getGeneratedBrokerage().hashCode());
        result = prime * result + ((getGainedBrokerage() == null) ? 0 : getGainedBrokerage().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table brokerage
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        userId("user_id", "userId", "INTEGER", false),
        generatedBrokerage("generated_brokerage", "generatedBrokerage", "DECIMAL", false),
        gainedBrokerage("gained_brokerage", "gainedBrokerage", "DECIMAL", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table brokerage
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table brokerage
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table brokerage
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table brokerage
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table brokerage
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table brokerage
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table brokerage
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table brokerage
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table brokerage
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table brokerage
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table brokerage
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table brokerage
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table brokerage
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table brokerage
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table brokerage
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table brokerage
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}