package com.cqjtu.sc.authservice.db.domain;

import java.util.ArrayList;
import java.util.Arrays;

public class AdminOperator {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_operator.operator_id
     *
     * @mbg.generated
     */
    private Integer operatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_operator.actor_id
     *
     * @mbg.generated
     */
    private Integer actorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_operator.operator_account
     *
     * @mbg.generated
     */
    private String operatorAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_operator.operator_password
     *
     * @mbg.generated
     */
    private String operatorPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_operator.operator_isavailable
     *
     * @mbg.generated
     */
    private Integer operatorIsavailable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_operator.supplier_id
     *
     * @mbg.generated
     */
    private Integer supplierId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_operator.operator_id
     *
     * @return the value of admin_operator.operator_id
     *
     * @mbg.generated
     */
    public Integer getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_operator.operator_id
     *
     * @param operatorId the value for admin_operator.operator_id
     *
     * @mbg.generated
     */
    public void setOperatorId(Integer operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_operator.actor_id
     *
     * @return the value of admin_operator.actor_id
     *
     * @mbg.generated
     */
    public Integer getActorId() {
        return actorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_operator.actor_id
     *
     * @param actorId the value for admin_operator.actor_id
     *
     * @mbg.generated
     */
    public void setActorId(Integer actorId) {
        this.actorId = actorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_operator.operator_account
     *
     * @return the value of admin_operator.operator_account
     *
     * @mbg.generated
     */
    public String getOperatorAccount() {
        return operatorAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_operator.operator_account
     *
     * @param operatorAccount the value for admin_operator.operator_account
     *
     * @mbg.generated
     */
    public void setOperatorAccount(String operatorAccount) {
        this.operatorAccount = operatorAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_operator.operator_password
     *
     * @return the value of admin_operator.operator_password
     *
     * @mbg.generated
     */
    public String getOperatorPassword() {
        return operatorPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_operator.operator_password
     *
     * @param operatorPassword the value for admin_operator.operator_password
     *
     * @mbg.generated
     */
    public void setOperatorPassword(String operatorPassword) {
        this.operatorPassword = operatorPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_operator.operator_isavailable
     *
     * @return the value of admin_operator.operator_isavailable
     *
     * @mbg.generated
     */
    public Integer getOperatorIsavailable() {
        return operatorIsavailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_operator.operator_isavailable
     *
     * @param operatorIsavailable the value for admin_operator.operator_isavailable
     *
     * @mbg.generated
     */
    public void setOperatorIsavailable(Integer operatorIsavailable) {
        this.operatorIsavailable = operatorIsavailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_operator.supplier_id
     *
     * @return the value of admin_operator.supplier_id
     *
     * @mbg.generated
     */
    public Integer getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_operator.supplier_id
     *
     * @param supplierId the value for admin_operator.supplier_id
     *
     * @mbg.generated
     */
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_operator
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", operatorId=").append(operatorId);
        sb.append(", actorId=").append(actorId);
        sb.append(", operatorAccount=").append(operatorAccount);
        sb.append(", operatorPassword=").append(operatorPassword);
        sb.append(", operatorIsavailable=").append(operatorIsavailable);
        sb.append(", supplierId=").append(supplierId);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_operator
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AdminOperator other = (AdminOperator) that;
        return (this.getOperatorId() == null ? other.getOperatorId() == null : this.getOperatorId().equals(other.getOperatorId()))
            && (this.getActorId() == null ? other.getActorId() == null : this.getActorId().equals(other.getActorId()))
            && (this.getOperatorAccount() == null ? other.getOperatorAccount() == null : this.getOperatorAccount().equals(other.getOperatorAccount()))
            && (this.getOperatorPassword() == null ? other.getOperatorPassword() == null : this.getOperatorPassword().equals(other.getOperatorPassword()))
            && (this.getOperatorIsavailable() == null ? other.getOperatorIsavailable() == null : this.getOperatorIsavailable().equals(other.getOperatorIsavailable()))
            && (this.getSupplierId() == null ? other.getSupplierId() == null : this.getSupplierId().equals(other.getSupplierId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_operator
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOperatorId() == null) ? 0 : getOperatorId().hashCode());
        result = prime * result + ((getActorId() == null) ? 0 : getActorId().hashCode());
        result = prime * result + ((getOperatorAccount() == null) ? 0 : getOperatorAccount().hashCode());
        result = prime * result + ((getOperatorPassword() == null) ? 0 : getOperatorPassword().hashCode());
        result = prime * result + ((getOperatorIsavailable() == null) ? 0 : getOperatorIsavailable().hashCode());
        result = prime * result + ((getSupplierId() == null) ? 0 : getSupplierId().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table admin_operator
     *
     * @mbg.generated
     */
    public enum Column {
        operatorId("operator_id", "operatorId", "INTEGER", false),
        actorId("actor_id", "actorId", "INTEGER", false),
        operatorAccount("operator_account", "operatorAccount", "VARCHAR", false),
        operatorPassword("operator_password", "operatorPassword", "VARCHAR", false),
        operatorIsavailable("operator_isavailable", "operatorIsavailable", "INTEGER", false),
        supplierId("supplier_id", "supplierId", "INTEGER", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table admin_operator
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table admin_operator
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table admin_operator
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table admin_operator
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table admin_operator
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table admin_operator
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table admin_operator
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table admin_operator
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table admin_operator
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table admin_operator
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table admin_operator
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table admin_operator
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table admin_operator
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table admin_operator
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table admin_operator
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table admin_operator
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}