package com.cqjtu.sc.authservice.db.domain;

import java.util.ArrayList;
import java.util.Arrays;

public class AdminAuthority {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_authority.authority_id
     *
     * @mbg.generated
     */
    private Integer authorityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_authority.group_id
     *
     * @mbg.generated
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_authority.authority_name
     *
     * @mbg.generated
     */
    private String authorityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_authority.authority_address
     *
     * @mbg.generated
     */
    private String authorityAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_authority.des
     *
     * @mbg.generated
     */
    private String des;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_authority.authority_id
     *
     * @return the value of admin_authority.authority_id
     *
     * @mbg.generated
     */
    public Integer getAuthorityId() {
        return authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_authority.authority_id
     *
     * @param authorityId the value for admin_authority.authority_id
     *
     * @mbg.generated
     */
    public void setAuthorityId(Integer authorityId) {
        this.authorityId = authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_authority.group_id
     *
     * @return the value of admin_authority.group_id
     *
     * @mbg.generated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_authority.group_id
     *
     * @param groupId the value for admin_authority.group_id
     *
     * @mbg.generated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_authority.authority_name
     *
     * @return the value of admin_authority.authority_name
     *
     * @mbg.generated
     */
    public String getAuthorityName() {
        return authorityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_authority.authority_name
     *
     * @param authorityName the value for admin_authority.authority_name
     *
     * @mbg.generated
     */
    public void setAuthorityName(String authorityName) {
        this.authorityName = authorityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_authority.authority_address
     *
     * @return the value of admin_authority.authority_address
     *
     * @mbg.generated
     */
    public String getAuthorityAddress() {
        return authorityAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_authority.authority_address
     *
     * @param authorityAddress the value for admin_authority.authority_address
     *
     * @mbg.generated
     */
    public void setAuthorityAddress(String authorityAddress) {
        this.authorityAddress = authorityAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_authority.des
     *
     * @return the value of admin_authority.des
     *
     * @mbg.generated
     */
    public String getDes() {
        return des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_authority.des
     *
     * @param des the value for admin_authority.des
     *
     * @mbg.generated
     */
    public void setDes(String des) {
        this.des = des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_authority
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", authorityId=").append(authorityId);
        sb.append(", groupId=").append(groupId);
        sb.append(", authorityName=").append(authorityName);
        sb.append(", authorityAddress=").append(authorityAddress);
        sb.append(", des=").append(des);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_authority
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AdminAuthority other = (AdminAuthority) that;
        return (this.getAuthorityId() == null ? other.getAuthorityId() == null : this.getAuthorityId().equals(other.getAuthorityId()))
            && (this.getGroupId() == null ? other.getGroupId() == null : this.getGroupId().equals(other.getGroupId()))
            && (this.getAuthorityName() == null ? other.getAuthorityName() == null : this.getAuthorityName().equals(other.getAuthorityName()))
            && (this.getAuthorityAddress() == null ? other.getAuthorityAddress() == null : this.getAuthorityAddress().equals(other.getAuthorityAddress()))
            && (this.getDes() == null ? other.getDes() == null : this.getDes().equals(other.getDes()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_authority
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAuthorityId() == null) ? 0 : getAuthorityId().hashCode());
        result = prime * result + ((getGroupId() == null) ? 0 : getGroupId().hashCode());
        result = prime * result + ((getAuthorityName() == null) ? 0 : getAuthorityName().hashCode());
        result = prime * result + ((getAuthorityAddress() == null) ? 0 : getAuthorityAddress().hashCode());
        result = prime * result + ((getDes() == null) ? 0 : getDes().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table admin_authority
     *
     * @mbg.generated
     */
    public enum Column {
        authorityId("authority_id", "authorityId", "INTEGER", false),
        groupId("group_id", "groupId", "INTEGER", false),
        authorityName("authority_name", "authorityName", "VARCHAR", false),
        authorityAddress("authority_address", "authorityAddress", "VARCHAR", false),
        des("des", "des", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table admin_authority
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table admin_authority
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table admin_authority
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table admin_authority
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table admin_authority
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table admin_authority
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table admin_authority
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table admin_authority
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table admin_authority
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table admin_authority
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table admin_authority
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table admin_authority
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table admin_authority
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table admin_authority
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table admin_authority
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table admin_authority
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}