package com.cqjtu.sc.authservice.db.domain;

import java.util.ArrayList;
import java.util.Arrays;

public class AdminOperatorAuthority {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_operator_authority.operator_auth_id
     *
     * @mbg.generated
     */
    private Integer operatorAuthId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_operator_authority.operator_id
     *
     * @mbg.generated
     */
    private Integer operatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_operator_authority.authority_id
     *
     * @mbg.generated
     */
    private Integer authorityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_operator_authority.operator_auth_id
     *
     * @return the value of admin_operator_authority.operator_auth_id
     *
     * @mbg.generated
     */
    public Integer getOperatorAuthId() {
        return operatorAuthId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_operator_authority.operator_auth_id
     *
     * @param operatorAuthId the value for admin_operator_authority.operator_auth_id
     *
     * @mbg.generated
     */
    public void setOperatorAuthId(Integer operatorAuthId) {
        this.operatorAuthId = operatorAuthId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_operator_authority.operator_id
     *
     * @return the value of admin_operator_authority.operator_id
     *
     * @mbg.generated
     */
    public Integer getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_operator_authority.operator_id
     *
     * @param operatorId the value for admin_operator_authority.operator_id
     *
     * @mbg.generated
     */
    public void setOperatorId(Integer operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_operator_authority.authority_id
     *
     * @return the value of admin_operator_authority.authority_id
     *
     * @mbg.generated
     */
    public Integer getAuthorityId() {
        return authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_operator_authority.authority_id
     *
     * @param authorityId the value for admin_operator_authority.authority_id
     *
     * @mbg.generated
     */
    public void setAuthorityId(Integer authorityId) {
        this.authorityId = authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_operator_authority
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", operatorAuthId=").append(operatorAuthId);
        sb.append(", operatorId=").append(operatorId);
        sb.append(", authorityId=").append(authorityId);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_operator_authority
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AdminOperatorAuthority other = (AdminOperatorAuthority) that;
        return (this.getOperatorAuthId() == null ? other.getOperatorAuthId() == null : this.getOperatorAuthId().equals(other.getOperatorAuthId()))
            && (this.getOperatorId() == null ? other.getOperatorId() == null : this.getOperatorId().equals(other.getOperatorId()))
            && (this.getAuthorityId() == null ? other.getAuthorityId() == null : this.getAuthorityId().equals(other.getAuthorityId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_operator_authority
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOperatorAuthId() == null) ? 0 : getOperatorAuthId().hashCode());
        result = prime * result + ((getOperatorId() == null) ? 0 : getOperatorId().hashCode());
        result = prime * result + ((getAuthorityId() == null) ? 0 : getAuthorityId().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table admin_operator_authority
     *
     * @mbg.generated
     */
    public enum Column {
        operatorAuthId("operator_auth_id", "operatorAuthId", "INTEGER", false),
        operatorId("operator_id", "operatorId", "INTEGER", false),
        authorityId("authority_id", "authorityId", "INTEGER", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table admin_operator_authority
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table admin_operator_authority
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table admin_operator_authority
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table admin_operator_authority
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table admin_operator_authority
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table admin_operator_authority
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table admin_operator_authority
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table admin_operator_authority
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table admin_operator_authority
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table admin_operator_authority
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table admin_operator_authority
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table admin_operator_authority
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table admin_operator_authority
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table admin_operator_authority
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table admin_operator_authority
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table admin_operator_authority
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}