package com.cqjtu.sc.authservice.db.dao;

import com.cqjtu.sc.authservice.db.domain.AdminActorAuthority;
import com.cqjtu.sc.authservice.db.domain.AdminActorAuthorityExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface AdminActorAuthorityMapper {
    void batchInsert(List<AdminActorAuthority> list);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_actor_authority
     *
     * @mbg.generated
     */
    long countByExample(AdminActorAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_actor_authority
     *
     * @mbg.generated
     */
    int deleteByExample(AdminActorAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_actor_authority
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer ruleAuthId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_actor_authority
     *
     * @mbg.generated
     */
    int insert(AdminActorAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_actor_authority
     *
     * @mbg.generated
     */
    int insertSelective(AdminActorAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_actor_authority
     *
     * @mbg.generated
     */
    AdminActorAuthority selectOneByExample(AdminActorAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_actor_authority
     *
     * @mbg.generated
     */
    AdminActorAuthority selectOneByExampleSelective(@Param("example") AdminActorAuthorityExample example, @Param("selective") AdminActorAuthority.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_actor_authority
     *
     * @mbg.generated
     */
    List<AdminActorAuthority> selectByExampleSelective(@Param("example") AdminActorAuthorityExample example, @Param("selective") AdminActorAuthority.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_actor_authority
     *
     * @mbg.generated
     */
    List<AdminActorAuthority> selectByExample(AdminActorAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_actor_authority
     *
     * @mbg.generated
     */
    AdminActorAuthority selectByPrimaryKeySelective(@Param("ruleAuthId") Integer ruleAuthId, @Param("selective") AdminActorAuthority.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_actor_authority
     *
     * @mbg.generated
     */
    AdminActorAuthority selectByPrimaryKey(Integer ruleAuthId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_actor_authority
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AdminActorAuthority record, @Param("example") AdminActorAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_actor_authority
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AdminActorAuthority record, @Param("example") AdminActorAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_actor_authority
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AdminActorAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_actor_authority
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AdminActorAuthority record);
}