package com.cqjtu.sc.authservice.db.dao;

import com.cqjtu.sc.authservice.db.domain.AdminActor;
import com.cqjtu.sc.authservice.db.domain.AdminActorExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface AdminActorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_actor
     *
     * @mbg.generated
     */
    long countByExample(AdminActorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_actor
     *
     * @mbg.generated
     */
    int deleteByExample(AdminActorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_actor
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer actorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_actor
     *
     * @mbg.generated
     */
    int insert(AdminActor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_actor
     *
     * @mbg.generated
     */
    int insertSelective(AdminActor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_actor
     *
     * @mbg.generated
     */
    AdminActor selectOneByExample(AdminActorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_actor
     *
     * @mbg.generated
     */
    AdminActor selectOneByExampleSelective(@Param("example") AdminActorExample example, @Param("selective") AdminActor.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_actor
     *
     * @mbg.generated
     */
    List<AdminActor> selectByExampleSelective(@Param("example") AdminActorExample example, @Param("selective") AdminActor.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_actor
     *
     * @mbg.generated
     */
    List<AdminActor> selectByExample(AdminActorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_actor
     *
     * @mbg.generated
     */
    AdminActor selectByPrimaryKeySelective(@Param("actorId") Integer actorId, @Param("selective") AdminActor.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_actor
     *
     * @mbg.generated
     */
    AdminActor selectByPrimaryKey(Integer actorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_actor
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AdminActor record, @Param("example") AdminActorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_actor
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AdminActor record, @Param("example") AdminActorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_actor
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AdminActor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_actor
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AdminActor record);
}