package com.cqjtu.sc.authservice.db.dao;

import com.cqjtu.sc.authservice.db.domain.AllSupplier;
import com.cqjtu.sc.authservice.db.domain.AllSupplierExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface AllSupplierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_supplier
     *
     * @mbg.generated
     */
    long countByExample(AllSupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_supplier
     *
     * @mbg.generated
     */
    int deleteByExample(AllSupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_supplier
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer supplierId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_supplier
     *
     * @mbg.generated
     */
    int insert(AllSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_supplier
     *
     * @mbg.generated
     */
    int insertSelective(AllSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_supplier
     *
     * @mbg.generated
     */
    AllSupplier selectOneByExample(AllSupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_supplier
     *
     * @mbg.generated
     */
    AllSupplier selectOneByExampleSelective(@Param("example") AllSupplierExample example, @Param("selective") AllSupplier.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_supplier
     *
     * @mbg.generated
     */
    List<AllSupplier> selectByExampleSelective(@Param("example") AllSupplierExample example, @Param("selective") AllSupplier.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_supplier
     *
     * @mbg.generated
     */
    List<AllSupplier> selectByExample(AllSupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_supplier
     *
     * @mbg.generated
     */
    AllSupplier selectByPrimaryKeySelective(@Param("supplierId") Integer supplierId, @Param("selective") AllSupplier.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_supplier
     *
     * @mbg.generated
     */
    AllSupplier selectByPrimaryKey(Integer supplierId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_supplier
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AllSupplier record, @Param("example") AllSupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_supplier
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AllSupplier record, @Param("example") AllSupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_supplier
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AllSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_supplier
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AllSupplier record);
}