spring:
  application:
    name: social-commerce-config
  profiles:
    active: native #启用本地配置文件
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/ #配置文件扫描目录

server:
  port: 8000 #服务端口