spring:
  application:
    name: social-commerce-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/ChunyuePeng/spring-cloud-config-repo
          search-paths: dep


server:
  port: 8000 #服务端口
