package com.cqjtu.sc.admin.goods.db.dao;

import com.cqjtu.sc.admin.goods.db.domain.AllCarrigeRule;
import com.cqjtu.sc.admin.goods.db.domain.AllCarrigeRuleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AllCarrigeRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_carrige_rule
     *
     * @mbg.generated
     */
    long countByExample(AllCarrigeRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_carrige_rule
     *
     * @mbg.generated
     */
    int deleteByExample(AllCarrigeRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_carrige_rule
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer carriageRuleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_carrige_rule
     *
     * @mbg.generated
     */
    int insert(AllCarrigeRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_carrige_rule
     *
     * @mbg.generated
     */
    int insertSelective(AllCarrigeRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_carrige_rule
     *
     * @mbg.generated
     */
    AllCarrigeRule selectOneByExample(AllCarrigeRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_carrige_rule
     *
     * @mbg.generated
     */
    AllCarrigeRule selectOneByExampleSelective(@Param("example") AllCarrigeRuleExample example, @Param("selective") AllCarrigeRule.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_carrige_rule
     *
     * @mbg.generated
     */
    List<AllCarrigeRule> selectByExampleSelective(@Param("example") AllCarrigeRuleExample example, @Param("selective") AllCarrigeRule.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_carrige_rule
     *
     * @mbg.generated
     */
    List<AllCarrigeRule> selectByExample(AllCarrigeRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_carrige_rule
     *
     * @mbg.generated
     */
    AllCarrigeRule selectByPrimaryKeySelective(@Param("carriageRuleId") Integer carriageRuleId, @Param("selective") AllCarrigeRule.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_carrige_rule
     *
     * @mbg.generated
     */
    AllCarrigeRule selectByPrimaryKey(Integer carriageRuleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_carrige_rule
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AllCarrigeRule record, @Param("example") AllCarrigeRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_carrige_rule
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AllCarrigeRule record, @Param("example") AllCarrigeRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_carrige_rule
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AllCarrigeRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_carrige_rule
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AllCarrigeRule record);
}