package com.cqjtu.sc.admin.goods.db.dao;

import com.cqjtu.sc.admin.goods.db.domain.AllCarrigeRuleConsist;
import com.cqjtu.sc.admin.goods.db.domain.AllCarrigeRuleConsistExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AllCarrigeRuleConsistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_carrige_rule_consist
     *
     * @mbg.generated
     */
    long countByExample(AllCarrigeRuleConsistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_carrige_rule_consist
     *
     * @mbg.generated
     */
    int deleteByExample(AllCarrigeRuleConsistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_carrige_rule_consist
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer carrigeRuleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_carrige_rule_consist
     *
     * @mbg.generated
     */
    int insert(AllCarrigeRuleConsist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_carrige_rule_consist
     *
     * @mbg.generated
     */
    int insertSelective(AllCarrigeRuleConsist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_carrige_rule_consist
     *
     * @mbg.generated
     */
    AllCarrigeRuleConsist selectOneByExample(AllCarrigeRuleConsistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_carrige_rule_consist
     *
     * @mbg.generated
     */
    AllCarrigeRuleConsist selectOneByExampleSelective(@Param("example") AllCarrigeRuleConsistExample example, @Param("selective") AllCarrigeRuleConsist.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_carrige_rule_consist
     *
     * @mbg.generated
     */
    List<AllCarrigeRuleConsist> selectByExampleSelective(@Param("example") AllCarrigeRuleConsistExample example, @Param("selective") AllCarrigeRuleConsist.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_carrige_rule_consist
     *
     * @mbg.generated
     */
    List<AllCarrigeRuleConsist> selectByExample(AllCarrigeRuleConsistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_carrige_rule_consist
     *
     * @mbg.generated
     */
    AllCarrigeRuleConsist selectByPrimaryKeySelective(@Param("carrigeRuleId") Integer carrigeRuleId, @Param("selective") AllCarrigeRuleConsist.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_carrige_rule_consist
     *
     * @mbg.generated
     */
    AllCarrigeRuleConsist selectByPrimaryKey(Integer carrigeRuleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_carrige_rule_consist
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AllCarrigeRuleConsist record, @Param("example") AllCarrigeRuleConsistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_carrige_rule_consist
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AllCarrigeRuleConsist record, @Param("example") AllCarrigeRuleConsistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_carrige_rule_consist
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AllCarrigeRuleConsist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_carrige_rule_consist
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AllCarrigeRuleConsist record);
}