package com.cqjtu.sc.admin.goods.db.dao;

import com.cqjtu.sc.admin.goods.db.domain.AllExtentionAtt;
import com.cqjtu.sc.admin.goods.db.domain.AllExtentionAttExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AllExtentionAttMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_extention_att
     *
     * @mbg.generated
     */
    long countByExample(AllExtentionAttExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_extention_att
     *
     * @mbg.generated
     */
    int deleteByExample(AllExtentionAttExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_extention_att
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer extensionAttId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_extention_att
     *
     * @mbg.generated
     */
    int insert(AllExtentionAtt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_extention_att
     *
     * @mbg.generated
     */
    int insertSelective(AllExtentionAtt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_extention_att
     *
     * @mbg.generated
     */
    AllExtentionAtt selectOneByExample(AllExtentionAttExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_extention_att
     *
     * @mbg.generated
     */
    AllExtentionAtt selectOneByExampleSelective(@Param("example") AllExtentionAttExample example, @Param("selective") AllExtentionAtt.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_extention_att
     *
     * @mbg.generated
     */
    List<AllExtentionAtt> selectByExampleSelective(@Param("example") AllExtentionAttExample example, @Param("selective") AllExtentionAtt.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_extention_att
     *
     * @mbg.generated
     */
    List<AllExtentionAtt> selectByExample(AllExtentionAttExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_extention_att
     *
     * @mbg.generated
     */
    AllExtentionAtt selectByPrimaryKeySelective(@Param("extensionAttId") Integer extensionAttId, @Param("selective") AllExtentionAtt.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_extention_att
     *
     * @mbg.generated
     */
    AllExtentionAtt selectByPrimaryKey(Integer extensionAttId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_extention_att
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AllExtentionAtt record, @Param("example") AllExtentionAttExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_extention_att
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AllExtentionAtt record, @Param("example") AllExtentionAttExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_extention_att
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AllExtentionAtt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_extention_att
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AllExtentionAtt record);
}