package com.cqjtu.sc.admin.goods.db.dao;

import com.cqjtu.sc.admin.goods.db.domain.AllGoodsSpecifiImg;
import com.cqjtu.sc.admin.goods.db.domain.AllGoodsSpecifiImgExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface AllGoodsSpecifiImgMapper {
    int batchInsertImg(List<AllGoodsSpecifiImg> imgList);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_img
     *
     * @mbg.generated
     */
    long countByExample(AllGoodsSpecifiImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_img
     *
     * @mbg.generated
     */
    int deleteByExample(AllGoodsSpecifiImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_img
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long imgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_img
     *
     * @mbg.generated
     */
    int insert(AllGoodsSpecifiImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_img
     *
     * @mbg.generated
     */
    int insertSelective(AllGoodsSpecifiImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_img
     *
     * @mbg.generated
     */
    AllGoodsSpecifiImg selectOneByExample(AllGoodsSpecifiImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_img
     *
     * @mbg.generated
     */
    AllGoodsSpecifiImg selectOneByExampleSelective(@Param("example") AllGoodsSpecifiImgExample example, @Param("selective") AllGoodsSpecifiImg.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_img
     *
     * @mbg.generated
     */
    List<AllGoodsSpecifiImg> selectByExampleSelective(@Param("example") AllGoodsSpecifiImgExample example, @Param("selective") AllGoodsSpecifiImg.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_img
     *
     * @mbg.generated
     */
    List<AllGoodsSpecifiImg> selectByExample(AllGoodsSpecifiImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_img
     *
     * @mbg.generated
     */
    AllGoodsSpecifiImg selectByPrimaryKeySelective(@Param("imgId") Long imgId, @Param("selective") AllGoodsSpecifiImg.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_img
     *
     * @mbg.generated
     */
    AllGoodsSpecifiImg selectByPrimaryKey(Long imgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_img
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AllGoodsSpecifiImg record, @Param("example") AllGoodsSpecifiImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_img
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AllGoodsSpecifiImg record, @Param("example") AllGoodsSpecifiImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_img
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AllGoodsSpecifiImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_img
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AllGoodsSpecifiImg record);
}