package com.cqjtu.sc.admin.goods.db.dao;

import com.cqjtu.sc.admin.goods.db.domain.AllGoodsSpecification;
import com.cqjtu.sc.admin.goods.db.domain.AllGoodsSpecificationExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface AllGoodsSpecificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specification
     *
     * @mbg.generated
     */
    long countByExample(AllGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specification
     *
     * @mbg.generated
     */
    int deleteByExample(AllGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specification
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer goodsSpecifiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specification
     *
     * @mbg.generated
     */
    int insert(AllGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specification
     *
     * @mbg.generated
     */
    int insertSelective(AllGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specification
     *
     * @mbg.generated
     */
    AllGoodsSpecification selectOneByExample(AllGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specification
     *
     * @mbg.generated
     */
    AllGoodsSpecification selectOneByExampleSelective(@Param("example") AllGoodsSpecificationExample example, @Param("selective") AllGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specification
     *
     * @mbg.generated
     */
    List<AllGoodsSpecification> selectByExampleSelective(@Param("example") AllGoodsSpecificationExample example, @Param("selective") AllGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specification
     *
     * @mbg.generated
     */
    List<AllGoodsSpecification> selectByExample(AllGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specification
     *
     * @mbg.generated
     */
    AllGoodsSpecification selectByPrimaryKeySelective(@Param("goodsSpecifiId") Integer goodsSpecifiId, @Param("selective") AllGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specification
     *
     * @mbg.generated
     */
    AllGoodsSpecification selectByPrimaryKey(Integer goodsSpecifiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specification
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AllGoodsSpecification record, @Param("example") AllGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specification
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AllGoodsSpecification record, @Param("example") AllGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specification
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AllGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specification
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AllGoodsSpecification record);
}