package com.cqjtu.sc.admin.goods.db.dao;

import com.cqjtu.sc.admin.goods.db.domain.AllGoodsCategory;
import com.cqjtu.sc.admin.goods.db.domain.AllGoodsCategoryExample;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface AllGoodsCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_category
     *
     * @mbg.generated
     */
    long countByExample(AllGoodsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_category
     *
     * @mbg.generated
     */
    int deleteByExample(AllGoodsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_category
     *
     * @mbg.generated
     */
    int insert(AllGoodsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_category
     *
     * @mbg.generated
     */
    int insertSelective(AllGoodsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_category
     *
     * @mbg.generated
     */
    AllGoodsCategory selectOneByExample(AllGoodsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_category
     *
     * @mbg.generated
     */
    AllGoodsCategory selectOneByExampleSelective(@Param("example") AllGoodsCategoryExample example, @Param("selective") AllGoodsCategory.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_category
     *
     * @mbg.generated
     */
    List<AllGoodsCategory> selectByExampleSelective(@Param("example") AllGoodsCategoryExample example, @Param("selective") AllGoodsCategory.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_category
     *
     * @mbg.generated
     */
    List<AllGoodsCategory> selectByExample(AllGoodsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_category
     *
     * @mbg.generated
     */
    AllGoodsCategory selectByPrimaryKeySelective(@Param("categoryId") Integer categoryId, @Param("selective") AllGoodsCategory.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_category
     *
     * @mbg.generated
     */
    AllGoodsCategory selectByPrimaryKey(Integer categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AllGoodsCategory record, @Param("example") AllGoodsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AllGoodsCategory record, @Param("example") AllGoodsCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AllGoodsCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AllGoodsCategory record);
}