package com.cqjtu.sc.admin.goods.db.dao;

import com.cqjtu.sc.admin.goods.db.domain.AllGoodsSpecifiAttValue;
import com.cqjtu.sc.admin.goods.db.domain.AllGoodsSpecifiAttValueExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface AllGoodsSpecifiAttValueMapper {

    int batchInsertProduct(List<AllGoodsSpecifiAttValue> list);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_att_value
     *
     * @mbg.generated
     */
    long countByExample(AllGoodsSpecifiAttValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_att_value
     *
     * @mbg.generated
     */
    int deleteByExample(AllGoodsSpecifiAttValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_att_value
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_att_value
     *
     * @mbg.generated
     */
    int insert(AllGoodsSpecifiAttValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_att_value
     *
     * @mbg.generated
     */
    int insertSelective(AllGoodsSpecifiAttValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_att_value
     *
     * @mbg.generated
     */
    AllGoodsSpecifiAttValue selectOneByExample(AllGoodsSpecifiAttValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_att_value
     *
     * @mbg.generated
     */
    AllGoodsSpecifiAttValue selectOneByExampleSelective(@Param("example") AllGoodsSpecifiAttValueExample example, @Param("selective") AllGoodsSpecifiAttValue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_att_value
     *
     * @mbg.generated
     */
    List<AllGoodsSpecifiAttValue> selectByExampleSelective(@Param("example") AllGoodsSpecifiAttValueExample example, @Param("selective") AllGoodsSpecifiAttValue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_att_value
     *
     * @mbg.generated
     */
    List<AllGoodsSpecifiAttValue> selectByExample(AllGoodsSpecifiAttValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_att_value
     *
     * @mbg.generated
     */
    AllGoodsSpecifiAttValue selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AllGoodsSpecifiAttValue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_att_value
     *
     * @mbg.generated
     */
    AllGoodsSpecifiAttValue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_att_value
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AllGoodsSpecifiAttValue record, @Param("example") AllGoodsSpecifiAttValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_att_value
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AllGoodsSpecifiAttValue record, @Param("example") AllGoodsSpecifiAttValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_att_value
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AllGoodsSpecifiAttValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_att_value
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AllGoodsSpecifiAttValue record);
}