package com.cqjtu.sc.admin.goods.db.dao;

import com.cqjtu.sc.admin.goods.db.domain.AllGoodsExtensionAttValue;
import com.cqjtu.sc.admin.goods.db.domain.AllGoodsExtensionAttValueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AllGoodsExtensionAttValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_extension_att_value
     *
     * @mbg.generated
     */
    long countByExample(AllGoodsExtensionAttValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_extension_att_value
     *
     * @mbg.generated
     */
    int deleteByExample(AllGoodsExtensionAttValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_extension_att_value
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer extensionValueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_extension_att_value
     *
     * @mbg.generated
     */
    int insert(AllGoodsExtensionAttValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_extension_att_value
     *
     * @mbg.generated
     */
    int insertSelective(AllGoodsExtensionAttValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_extension_att_value
     *
     * @mbg.generated
     */
    AllGoodsExtensionAttValue selectOneByExample(AllGoodsExtensionAttValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_extension_att_value
     *
     * @mbg.generated
     */
    AllGoodsExtensionAttValue selectOneByExampleSelective(@Param("example") AllGoodsExtensionAttValueExample example, @Param("selective") AllGoodsExtensionAttValue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_extension_att_value
     *
     * @mbg.generated
     */
    List<AllGoodsExtensionAttValue> selectByExampleSelective(@Param("example") AllGoodsExtensionAttValueExample example, @Param("selective") AllGoodsExtensionAttValue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_extension_att_value
     *
     * @mbg.generated
     */
    List<AllGoodsExtensionAttValue> selectByExample(AllGoodsExtensionAttValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_extension_att_value
     *
     * @mbg.generated
     */
    AllGoodsExtensionAttValue selectByPrimaryKeySelective(@Param("extensionValueId") Integer extensionValueId, @Param("selective") AllGoodsExtensionAttValue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_extension_att_value
     *
     * @mbg.generated
     */
    AllGoodsExtensionAttValue selectByPrimaryKey(Integer extensionValueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_extension_att_value
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AllGoodsExtensionAttValue record, @Param("example") AllGoodsExtensionAttValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_extension_att_value
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AllGoodsExtensionAttValue record, @Param("example") AllGoodsExtensionAttValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_extension_att_value
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AllGoodsExtensionAttValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_extension_att_value
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AllGoodsExtensionAttValue record);
}