package com.cqjtu.sc.admin.goods.db.dao;

import com.cqjtu.sc.admin.goods.db.domain.AllGoodsBoard;
import com.cqjtu.sc.admin.goods.db.domain.AllGoodsBoardExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AllGoodsBoardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_board
     *
     * @mbg.generated
     */
    long countByExample(AllGoodsBoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_board
     *
     * @mbg.generated
     */
    int deleteByExample(AllGoodsBoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_board
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer boardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_board
     *
     * @mbg.generated
     */
    int insert(AllGoodsBoard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_board
     *
     * @mbg.generated
     */
    int insertSelective(AllGoodsBoard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_board
     *
     * @mbg.generated
     */
    AllGoodsBoard selectOneByExample(AllGoodsBoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_board
     *
     * @mbg.generated
     */
    AllGoodsBoard selectOneByExampleSelective(@Param("example") AllGoodsBoardExample example, @Param("selective") AllGoodsBoard.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_board
     *
     * @mbg.generated
     */
    List<AllGoodsBoard> selectByExampleSelective(@Param("example") AllGoodsBoardExample example, @Param("selective") AllGoodsBoard.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_board
     *
     * @mbg.generated
     */
    List<AllGoodsBoard> selectByExample(AllGoodsBoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_board
     *
     * @mbg.generated
     */
    AllGoodsBoard selectByPrimaryKeySelective(@Param("boardId") Integer boardId, @Param("selective") AllGoodsBoard.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_board
     *
     * @mbg.generated
     */
    AllGoodsBoard selectByPrimaryKey(Integer boardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_board
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AllGoodsBoard record, @Param("example") AllGoodsBoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_board
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AllGoodsBoard record, @Param("example") AllGoodsBoardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_board
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AllGoodsBoard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_board
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AllGoodsBoard record);
}