package com.cqjtu.sc.admin.goods.db.dao;

import com.cqjtu.sc.admin.goods.db.domain.AllGoodsBrand;
import com.cqjtu.sc.admin.goods.db.domain.AllGoodsBrandExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AllGoodsBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_brand
     *
     * @mbg.generated
     */
    long countByExample(AllGoodsBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_brand
     *
     * @mbg.generated
     */
    int deleteByExample(AllGoodsBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_brand
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer brandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_brand
     *
     * @mbg.generated
     */
    int insert(AllGoodsBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_brand
     *
     * @mbg.generated
     */
    int insertSelective(AllGoodsBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_brand
     *
     * @mbg.generated
     */
    AllGoodsBrand selectOneByExample(AllGoodsBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_brand
     *
     * @mbg.generated
     */
    AllGoodsBrand selectOneByExampleSelective(@Param("example") AllGoodsBrandExample example, @Param("selective") AllGoodsBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_brand
     *
     * @mbg.generated
     */
    List<AllGoodsBrand> selectByExampleSelective(@Param("example") AllGoodsBrandExample example, @Param("selective") AllGoodsBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_brand
     *
     * @mbg.generated
     */
    List<AllGoodsBrand> selectByExample(AllGoodsBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_brand
     *
     * @mbg.generated
     */
    AllGoodsBrand selectByPrimaryKeySelective(@Param("brandId") Integer brandId, @Param("selective") AllGoodsBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_brand
     *
     * @mbg.generated
     */
    AllGoodsBrand selectByPrimaryKey(Integer brandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_brand
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AllGoodsBrand record, @Param("example") AllGoodsBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_brand
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AllGoodsBrand record, @Param("example") AllGoodsBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AllGoodsBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AllGoodsBrand record);
}