package com.cqjtu.sc.admin.goods.db.dao;

import com.cqjtu.sc.admin.goods.db.domain.AllGoodsCatExtenAtt;
import com.cqjtu.sc.admin.goods.db.domain.AllGoodsCatExtenAttExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AllGoodsCatExtenAttMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_cat_exten_att
     *
     * @mbg.generated
     */
    long countByExample(AllGoodsCatExtenAttExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_cat_exten_att
     *
     * @mbg.generated
     */
    int deleteByExample(AllGoodsCatExtenAttExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_cat_exten_att
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_cat_exten_att
     *
     * @mbg.generated
     */
    int insert(AllGoodsCatExtenAtt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_cat_exten_att
     *
     * @mbg.generated
     */
    int insertSelective(AllGoodsCatExtenAtt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_cat_exten_att
     *
     * @mbg.generated
     */
    AllGoodsCatExtenAtt selectOneByExample(AllGoodsCatExtenAttExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_cat_exten_att
     *
     * @mbg.generated
     */
    AllGoodsCatExtenAtt selectOneByExampleSelective(@Param("example") AllGoodsCatExtenAttExample example, @Param("selective") AllGoodsCatExtenAtt.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_cat_exten_att
     *
     * @mbg.generated
     */
    List<AllGoodsCatExtenAtt> selectByExampleSelective(@Param("example") AllGoodsCatExtenAttExample example, @Param("selective") AllGoodsCatExtenAtt.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_cat_exten_att
     *
     * @mbg.generated
     */
    List<AllGoodsCatExtenAtt> selectByExample(AllGoodsCatExtenAttExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_cat_exten_att
     *
     * @mbg.generated
     */
    AllGoodsCatExtenAtt selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") AllGoodsCatExtenAtt.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_cat_exten_att
     *
     * @mbg.generated
     */
    AllGoodsCatExtenAtt selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_cat_exten_att
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AllGoodsCatExtenAtt record, @Param("example") AllGoodsCatExtenAttExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_cat_exten_att
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AllGoodsCatExtenAtt record, @Param("example") AllGoodsCatExtenAttExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_cat_exten_att
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AllGoodsCatExtenAtt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_cat_exten_att
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AllGoodsCatExtenAtt record);
}