package com.cqjtu.sc.goodsrecommendservice.db.dao;

import com.cqjtu.sc.goodsrecommendservice.db.domain.AllGoodsSpecifiAttValue;
import com.cqjtu.sc.goodsrecommendservice.db.domain.AllGoodsSpecifiAttValueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AllGoodsSpecifiAttValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_att_value
     *
     * @mbg.generated
     */
    long countByExample(AllGoodsSpecifiAttValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_att_value
     *
     * @mbg.generated
     */
    int deleteByExample(AllGoodsSpecifiAttValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_att_value
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer specifiValueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_att_value
     *
     * @mbg.generated
     */
    int insert(AllGoodsSpecifiAttValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_att_value
     *
     * @mbg.generated
     */
    int insertSelective(AllGoodsSpecifiAttValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_att_value
     *
     * @mbg.generated
     */
    AllGoodsSpecifiAttValue selectOneByExample(AllGoodsSpecifiAttValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_att_value
     *
     * @mbg.generated
     */
    AllGoodsSpecifiAttValue selectOneByExampleSelective(@Param("example") AllGoodsSpecifiAttValueExample example, @Param("selective") AllGoodsSpecifiAttValue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_att_value
     *
     * @mbg.generated
     */
    List<AllGoodsSpecifiAttValue> selectByExampleSelective(@Param("example") AllGoodsSpecifiAttValueExample example, @Param("selective") AllGoodsSpecifiAttValue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_att_value
     *
     * @mbg.generated
     */
    List<AllGoodsSpecifiAttValue> selectByExample(AllGoodsSpecifiAttValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_att_value
     *
     * @mbg.generated
     */
    AllGoodsSpecifiAttValue selectByPrimaryKeySelective(@Param("specifiValueId") Integer specifiValueId, @Param("selective") AllGoodsSpecifiAttValue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_att_value
     *
     * @mbg.generated
     */
    AllGoodsSpecifiAttValue selectByPrimaryKey(Integer specifiValueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_att_value
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AllGoodsSpecifiAttValue record, @Param("example") AllGoodsSpecifiAttValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_att_value
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AllGoodsSpecifiAttValue record, @Param("example") AllGoodsSpecifiAttValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_att_value
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AllGoodsSpecifiAttValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_specifi_att_value
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AllGoodsSpecifiAttValue record);
}