package com.cqjtu.sc.goodsrecommendservice.db.dao;

import com.cqjtu.sc.goodsrecommendservice.db.domain.AllGoodsInfo;
import com.cqjtu.sc.goodsrecommendservice.db.domain.AllGoodsInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface AllGoodsInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_info
     *
     * @mbg.generated
     */
    long countByExample(AllGoodsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_info
     *
     * @mbg.generated
     */
    int deleteByExample(AllGoodsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_info
     *
     * @mbg.generated
     */
    int insert(AllGoodsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_info
     *
     * @mbg.generated
     */
    int insertSelective(AllGoodsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_info
     *
     * @mbg.generated
     */
    AllGoodsInfo selectOneByExample(AllGoodsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_info
     *
     * @mbg.generated
     */
    AllGoodsInfo selectOneByExampleSelective(@Param("example") AllGoodsInfoExample example, @Param("selective") AllGoodsInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_info
     *
     * @mbg.generated
     */
    List<AllGoodsInfo> selectByExampleSelective(@Param("example") AllGoodsInfoExample example, @Param("selective") AllGoodsInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_info
     *
     * @mbg.generated
     */
    List<AllGoodsInfo> selectByExample(AllGoodsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_info
     *
     * @mbg.generated
     */
    AllGoodsInfo selectByPrimaryKeySelective(@Param("goodsId") Integer goodsId, @Param("selective") AllGoodsInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_info
     *
     * @mbg.generated
     */
    AllGoodsInfo selectByPrimaryKey(Integer goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AllGoodsInfo record, @Param("example") AllGoodsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AllGoodsInfo record, @Param("example") AllGoodsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AllGoodsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AllGoodsInfo record);
}