package com.cqjtu.sc.orderservice.db.dao;

import com.cqjtu.sc.orderservice.db.domain.AllOrder;
import com.cqjtu.sc.orderservice.db.domain.AllOrderExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface AllOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_order
     *
     * @mbg.generated
     */
    long countByExample(AllOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_order
     *
     * @mbg.generated
     */
    int deleteByExample(AllOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_order
     *
     * @mbg.generated
     */
    int insert(AllOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_order
     *
     * @mbg.generated
     */
    int insertSelective(AllOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_order
     *
     * @mbg.generated
     */
    AllOrder selectOneByExample(AllOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_order
     *
     * @mbg.generated
     */
    AllOrder selectOneByExampleSelective(@Param("example") AllOrderExample example, @Param("selective") AllOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_order
     *
     * @mbg.generated
     */
    List<AllOrder> selectByExampleSelective(@Param("example") AllOrderExample example, @Param("selective") AllOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_order
     *
     * @mbg.generated
     */
    List<AllOrder> selectByExample(AllOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_order
     *
     * @mbg.generated
     */
    AllOrder selectByPrimaryKeySelective(@Param("orderId") Integer orderId, @Param("selective") AllOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_order
     *
     * @mbg.generated
     */
    AllOrder selectByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AllOrder record, @Param("example") AllOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AllOrder record, @Param("example") AllOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AllOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AllOrder record);
}