package com.cqjtu.sc.orderservice.db.dao;

import com.cqjtu.sc.orderservice.db.domain.AllRegion;
import com.cqjtu.sc.orderservice.db.domain.AllRegionExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface AllRegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_region
     *
     * @mbg.generated
     */
    long countByExample(AllRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_region
     *
     * @mbg.generated
     */
    int deleteByExample(AllRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_region
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer regionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_region
     *
     * @mbg.generated
     */
    int insert(AllRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_region
     *
     * @mbg.generated
     */
    int insertSelective(AllRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_region
     *
     * @mbg.generated
     */
    AllRegion selectOneByExample(AllRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_region
     *
     * @mbg.generated
     */
    AllRegion selectOneByExampleSelective(@Param("example") AllRegionExample example, @Param("selective") AllRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_region
     *
     * @mbg.generated
     */
    List<AllRegion> selectByExampleSelective(@Param("example") AllRegionExample example, @Param("selective") AllRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_region
     *
     * @mbg.generated
     */
    List<AllRegion> selectByExample(AllRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_region
     *
     * @mbg.generated
     */
    AllRegion selectByPrimaryKeySelective(@Param("regionId") Integer regionId, @Param("selective") AllRegion.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_region
     *
     * @mbg.generated
     */
    AllRegion selectByPrimaryKey(Integer regionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_region
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AllRegion record, @Param("example") AllRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_region
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AllRegion record, @Param("example") AllRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_region
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AllRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_region
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AllRegion record);
}