package com.cqjtu.sc.orderservice.db.dao;

import com.cqjtu.sc.orderservice.db.domain.Brokerage;
import com.cqjtu.sc.orderservice.db.domain.BrokerageExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface BrokerageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brokerage
     *
     * @mbg.generated
     */
    long countByExample(BrokerageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brokerage
     *
     * @mbg.generated
     */
    int deleteByExample(BrokerageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brokerage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brokerage
     *
     * @mbg.generated
     */
    int insert(Brokerage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brokerage
     *
     * @mbg.generated
     */
    int insertSelective(Brokerage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brokerage
     *
     * @mbg.generated
     */
    Brokerage selectOneByExample(BrokerageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brokerage
     *
     * @mbg.generated
     */
    Brokerage selectOneByExampleSelective(@Param("example") BrokerageExample example, @Param("selective") Brokerage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brokerage
     *
     * @mbg.generated
     */
    List<Brokerage> selectByExampleSelective(@Param("example") BrokerageExample example, @Param("selective") Brokerage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brokerage
     *
     * @mbg.generated
     */
    List<Brokerage> selectByExample(BrokerageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brokerage
     *
     * @mbg.generated
     */
    Brokerage selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") Brokerage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brokerage
     *
     * @mbg.generated
     */
    Brokerage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brokerage
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Brokerage record, @Param("example") BrokerageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brokerage
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Brokerage record, @Param("example") BrokerageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brokerage
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Brokerage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brokerage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Brokerage record);
}