package com.cqjtu.sc.admin.goods.db.domain;

import java.util.ArrayList;
import java.util.List;

public class AllGoodsExtensionAttValueExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table all_goods_extension_att_value
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table all_goods_extension_att_value
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table all_goods_extension_att_value
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_extension_att_value
     *
     * @mbg.generated
     */
    public AllGoodsExtensionAttValueExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_extension_att_value
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_extension_att_value
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_extension_att_value
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_extension_att_value
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_extension_att_value
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_extension_att_value
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_extension_att_value
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_extension_att_value
     *
     * @mbg.generated
     */
    public AllGoodsExtensionAttValueExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_extension_att_value
     *
     * @mbg.generated
     */
    public AllGoodsExtensionAttValueExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_extension_att_value
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_extension_att_value
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_extension_att_value
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_extension_att_value
     *
     * @mbg.generated
     */
    public static Criteria newAndCreateCriteria() {
        AllGoodsExtensionAttValueExample example = new AllGoodsExtensionAttValueExample();
        return example.createCriteria();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_extension_att_value
     *
     * @mbg.generated
     */
    public AllGoodsExtensionAttValueExample when(boolean condition, IExampleWhen then) {
        if (condition) {
            then.example(this);
        }
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_goods_extension_att_value
     *
     * @mbg.generated
     */
    public AllGoodsExtensionAttValueExample when(boolean condition, IExampleWhen then, IExampleWhen otherwise) {
        if (condition) {
            then.example(this);
        } else {
            otherwise.example(this);
        }
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table all_goods_extension_att_value
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andExtensionValueIdIsNull() {
            addCriterion("extension_value_id is null");
            return (Criteria) this;
        }

        public Criteria andExtensionValueIdIsNotNull() {
            addCriterion("extension_value_id is not null");
            return (Criteria) this;
        }

        public Criteria andExtensionValueIdEqualTo(Integer value) {
            addCriterion("extension_value_id =", value, "extensionValueId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_goods_extension_att_value
         *
         * @mbg.generated
         */
        public Criteria andExtensionValueIdEqualToColumn(AllGoodsExtensionAttValue.Column column) {
            addCriterion(new StringBuilder("extension_value_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andExtensionValueIdNotEqualTo(Integer value) {
            addCriterion("extension_value_id <>", value, "extensionValueId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_goods_extension_att_value
         *
         * @mbg.generated
         */
        public Criteria andExtensionValueIdNotEqualToColumn(AllGoodsExtensionAttValue.Column column) {
            addCriterion(new StringBuilder("extension_value_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andExtensionValueIdGreaterThan(Integer value) {
            addCriterion("extension_value_id >", value, "extensionValueId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_goods_extension_att_value
         *
         * @mbg.generated
         */
        public Criteria andExtensionValueIdGreaterThanColumn(AllGoodsExtensionAttValue.Column column) {
            addCriterion(new StringBuilder("extension_value_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andExtensionValueIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("extension_value_id >=", value, "extensionValueId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_goods_extension_att_value
         *
         * @mbg.generated
         */
        public Criteria andExtensionValueIdGreaterThanOrEqualToColumn(AllGoodsExtensionAttValue.Column column) {
            addCriterion(new StringBuilder("extension_value_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andExtensionValueIdLessThan(Integer value) {
            addCriterion("extension_value_id <", value, "extensionValueId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_goods_extension_att_value
         *
         * @mbg.generated
         */
        public Criteria andExtensionValueIdLessThanColumn(AllGoodsExtensionAttValue.Column column) {
            addCriterion(new StringBuilder("extension_value_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andExtensionValueIdLessThanOrEqualTo(Integer value) {
            addCriterion("extension_value_id <=", value, "extensionValueId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_goods_extension_att_value
         *
         * @mbg.generated
         */
        public Criteria andExtensionValueIdLessThanOrEqualToColumn(AllGoodsExtensionAttValue.Column column) {
            addCriterion(new StringBuilder("extension_value_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andExtensionValueIdIn(List<Integer> values) {
            addCriterion("extension_value_id in", values, "extensionValueId");
            return (Criteria) this;
        }

        public Criteria andExtensionValueIdNotIn(List<Integer> values) {
            addCriterion("extension_value_id not in", values, "extensionValueId");
            return (Criteria) this;
        }

        public Criteria andExtensionValueIdBetween(Integer value1, Integer value2) {
            addCriterion("extension_value_id between", value1, value2, "extensionValueId");
            return (Criteria) this;
        }

        public Criteria andExtensionValueIdNotBetween(Integer value1, Integer value2) {
            addCriterion("extension_value_id not between", value1, value2, "extensionValueId");
            return (Criteria) this;
        }

        public Criteria andExtensionAttIdIsNull() {
            addCriterion("extension_att_id is null");
            return (Criteria) this;
        }

        public Criteria andExtensionAttIdIsNotNull() {
            addCriterion("extension_att_id is not null");
            return (Criteria) this;
        }

        public Criteria andExtensionAttIdEqualTo(Integer value) {
            addCriterion("extension_att_id =", value, "extensionAttId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_goods_extension_att_value
         *
         * @mbg.generated
         */
        public Criteria andExtensionAttIdEqualToColumn(AllGoodsExtensionAttValue.Column column) {
            addCriterion(new StringBuilder("extension_att_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andExtensionAttIdNotEqualTo(Integer value) {
            addCriterion("extension_att_id <>", value, "extensionAttId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_goods_extension_att_value
         *
         * @mbg.generated
         */
        public Criteria andExtensionAttIdNotEqualToColumn(AllGoodsExtensionAttValue.Column column) {
            addCriterion(new StringBuilder("extension_att_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andExtensionAttIdGreaterThan(Integer value) {
            addCriterion("extension_att_id >", value, "extensionAttId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_goods_extension_att_value
         *
         * @mbg.generated
         */
        public Criteria andExtensionAttIdGreaterThanColumn(AllGoodsExtensionAttValue.Column column) {
            addCriterion(new StringBuilder("extension_att_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andExtensionAttIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("extension_att_id >=", value, "extensionAttId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_goods_extension_att_value
         *
         * @mbg.generated
         */
        public Criteria andExtensionAttIdGreaterThanOrEqualToColumn(AllGoodsExtensionAttValue.Column column) {
            addCriterion(new StringBuilder("extension_att_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andExtensionAttIdLessThan(Integer value) {
            addCriterion("extension_att_id <", value, "extensionAttId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_goods_extension_att_value
         *
         * @mbg.generated
         */
        public Criteria andExtensionAttIdLessThanColumn(AllGoodsExtensionAttValue.Column column) {
            addCriterion(new StringBuilder("extension_att_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andExtensionAttIdLessThanOrEqualTo(Integer value) {
            addCriterion("extension_att_id <=", value, "extensionAttId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_goods_extension_att_value
         *
         * @mbg.generated
         */
        public Criteria andExtensionAttIdLessThanOrEqualToColumn(AllGoodsExtensionAttValue.Column column) {
            addCriterion(new StringBuilder("extension_att_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andExtensionAttIdIn(List<Integer> values) {
            addCriterion("extension_att_id in", values, "extensionAttId");
            return (Criteria) this;
        }

        public Criteria andExtensionAttIdNotIn(List<Integer> values) {
            addCriterion("extension_att_id not in", values, "extensionAttId");
            return (Criteria) this;
        }

        public Criteria andExtensionAttIdBetween(Integer value1, Integer value2) {
            addCriterion("extension_att_id between", value1, value2, "extensionAttId");
            return (Criteria) this;
        }

        public Criteria andExtensionAttIdNotBetween(Integer value1, Integer value2) {
            addCriterion("extension_att_id not between", value1, value2, "extensionAttId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIsNull() {
            addCriterion("goods_id is null");
            return (Criteria) this;
        }

        public Criteria andGoodsIdIsNotNull() {
            addCriterion("goods_id is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsIdEqualTo(Integer value) {
            addCriterion("goods_id =", value, "goodsId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_goods_extension_att_value
         *
         * @mbg.generated
         */
        public Criteria andGoodsIdEqualToColumn(AllGoodsExtensionAttValue.Column column) {
            addCriterion(new StringBuilder("goods_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotEqualTo(Integer value) {
            addCriterion("goods_id <>", value, "goodsId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_goods_extension_att_value
         *
         * @mbg.generated
         */
        public Criteria andGoodsIdNotEqualToColumn(AllGoodsExtensionAttValue.Column column) {
            addCriterion(new StringBuilder("goods_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGoodsIdGreaterThan(Integer value) {
            addCriterion("goods_id >", value, "goodsId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_goods_extension_att_value
         *
         * @mbg.generated
         */
        public Criteria andGoodsIdGreaterThanColumn(AllGoodsExtensionAttValue.Column column) {
            addCriterion(new StringBuilder("goods_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGoodsIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("goods_id >=", value, "goodsId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_goods_extension_att_value
         *
         * @mbg.generated
         */
        public Criteria andGoodsIdGreaterThanOrEqualToColumn(AllGoodsExtensionAttValue.Column column) {
            addCriterion(new StringBuilder("goods_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGoodsIdLessThan(Integer value) {
            addCriterion("goods_id <", value, "goodsId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_goods_extension_att_value
         *
         * @mbg.generated
         */
        public Criteria andGoodsIdLessThanColumn(AllGoodsExtensionAttValue.Column column) {
            addCriterion(new StringBuilder("goods_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGoodsIdLessThanOrEqualTo(Integer value) {
            addCriterion("goods_id <=", value, "goodsId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_goods_extension_att_value
         *
         * @mbg.generated
         */
        public Criteria andGoodsIdLessThanOrEqualToColumn(AllGoodsExtensionAttValue.Column column) {
            addCriterion(new StringBuilder("goods_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andGoodsIdIn(List<Integer> values) {
            addCriterion("goods_id in", values, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotIn(List<Integer> values) {
            addCriterion("goods_id not in", values, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdBetween(Integer value1, Integer value2) {
            addCriterion("goods_id between", value1, value2, "goodsId");
            return (Criteria) this;
        }

        public Criteria andGoodsIdNotBetween(Integer value1, Integer value2) {
            addCriterion("goods_id not between", value1, value2, "goodsId");
            return (Criteria) this;
        }

        public Criteria andExtensionAttValueIsNull() {
            addCriterion("extension_att_value is null");
            return (Criteria) this;
        }

        public Criteria andExtensionAttValueIsNotNull() {
            addCriterion("extension_att_value is not null");
            return (Criteria) this;
        }

        public Criteria andExtensionAttValueEqualTo(String value) {
            addCriterion("extension_att_value =", value, "extensionAttValue");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_goods_extension_att_value
         *
         * @mbg.generated
         */
        public Criteria andExtensionAttValueEqualToColumn(AllGoodsExtensionAttValue.Column column) {
            addCriterion(new StringBuilder("extension_att_value = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andExtensionAttValueNotEqualTo(String value) {
            addCriterion("extension_att_value <>", value, "extensionAttValue");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_goods_extension_att_value
         *
         * @mbg.generated
         */
        public Criteria andExtensionAttValueNotEqualToColumn(AllGoodsExtensionAttValue.Column column) {
            addCriterion(new StringBuilder("extension_att_value <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andExtensionAttValueGreaterThan(String value) {
            addCriterion("extension_att_value >", value, "extensionAttValue");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_goods_extension_att_value
         *
         * @mbg.generated
         */
        public Criteria andExtensionAttValueGreaterThanColumn(AllGoodsExtensionAttValue.Column column) {
            addCriterion(new StringBuilder("extension_att_value > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andExtensionAttValueGreaterThanOrEqualTo(String value) {
            addCriterion("extension_att_value >=", value, "extensionAttValue");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_goods_extension_att_value
         *
         * @mbg.generated
         */
        public Criteria andExtensionAttValueGreaterThanOrEqualToColumn(AllGoodsExtensionAttValue.Column column) {
            addCriterion(new StringBuilder("extension_att_value >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andExtensionAttValueLessThan(String value) {
            addCriterion("extension_att_value <", value, "extensionAttValue");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_goods_extension_att_value
         *
         * @mbg.generated
         */
        public Criteria andExtensionAttValueLessThanColumn(AllGoodsExtensionAttValue.Column column) {
            addCriterion(new StringBuilder("extension_att_value < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andExtensionAttValueLessThanOrEqualTo(String value) {
            addCriterion("extension_att_value <=", value, "extensionAttValue");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_goods_extension_att_value
         *
         * @mbg.generated
         */
        public Criteria andExtensionAttValueLessThanOrEqualToColumn(AllGoodsExtensionAttValue.Column column) {
            addCriterion(new StringBuilder("extension_att_value <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andExtensionAttValueLike(String value) {
            addCriterion("extension_att_value like", value, "extensionAttValue");
            return (Criteria) this;
        }

        public Criteria andExtensionAttValueNotLike(String value) {
            addCriterion("extension_att_value not like", value, "extensionAttValue");
            return (Criteria) this;
        }

        public Criteria andExtensionAttValueIn(List<String> values) {
            addCriterion("extension_att_value in", values, "extensionAttValue");
            return (Criteria) this;
        }

        public Criteria andExtensionAttValueNotIn(List<String> values) {
            addCriterion("extension_att_value not in", values, "extensionAttValue");
            return (Criteria) this;
        }

        public Criteria andExtensionAttValueBetween(String value1, String value2) {
            addCriterion("extension_att_value between", value1, value2, "extensionAttValue");
            return (Criteria) this;
        }

        public Criteria andExtensionAttValueNotBetween(String value1, String value2) {
            addCriterion("extension_att_value not between", value1, value2, "extensionAttValue");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table all_goods_extension_att_value
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table all_goods_extension_att_value
         *
         * @mbg.generated
         */
        private AllGoodsExtensionAttValueExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_goods_extension_att_value
         *
         * @mbg.generated
         */
        protected Criteria(AllGoodsExtensionAttValueExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_goods_extension_att_value
         *
         * @mbg.generated
         */
        public AllGoodsExtensionAttValueExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_goods_extension_att_value
         *
         * @mbg.generated
         */
        @Deprecated
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_goods_extension_att_value
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then) {
            if (condition) {
                then.criteria(this);
            }
            return this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_goods_extension_att_value
         *
         * @mbg.generated
         */
        public Criteria when(boolean condition, ICriteriaWhen then, ICriteriaWhen otherwise) {
            if (condition) {
                then.criteria(this);
            } else {
                otherwise.criteria(this);
            }
            return this;
        }

        @Deprecated
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table all_goods_extension_att_value
             *
             * @mbg.generated
             */
            Criteria add(Criteria add);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table all_goods_extension_att_value
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    public interface ICriteriaWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_goods_extension_att_value
         *
         * @mbg.generated
         */
        void criteria(Criteria criteria);
    }

    public interface IExampleWhen {
        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_goods_extension_att_value
         *
         * @mbg.generated
         */
        void example(com.cqjtu.sc.admin.goods.db.domain.AllGoodsExtensionAttValueExample example);
    }
}