package com.cqjtu.sc.admin.goods.db.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class AllSupplier {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_supplier.supplier_id
     *
     * @mbg.generated
     */
    private Integer supplierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_supplier.region_id
     *
     * @mbg.generated
     */
    private Integer regionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_supplier.supplier_name
     *
     * @mbg.generated
     */
    private String supplierName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_supplier.user_info_id
     *
     * @mbg.generated
     */
    private Integer userInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_supplier.contacts
     *
     * @mbg.generated
     */
    private String contacts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_supplier.tel
     *
     * @mbg.generated
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_supplier.supplier_desc
     *
     * @mbg.generated
     */
    private String supplierDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_supplier.saleman
     *
     * @mbg.generated
     */
    private String saleman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_supplier.supplier_add_man
     *
     * @mbg.generated
     */
    private String supplierAddMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_supplier.supplier_add_time
     *
     * @mbg.generated
     */
    private LocalDateTime supplierAddTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_supplier.supplier_last_modifier
     *
     * @mbg.generated
     */
    private String supplierLastModifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_supplier.supplier_last_edit_time
     *
     * @mbg.generated
     */
    private LocalDateTime supplierLastEditTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_supplier.supplier_id
     *
     * @return the value of all_supplier.supplier_id
     *
     * @mbg.generated
     */
    public Integer getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_supplier.supplier_id
     *
     * @param supplierId the value for all_supplier.supplier_id
     *
     * @mbg.generated
     */
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_supplier.region_id
     *
     * @return the value of all_supplier.region_id
     *
     * @mbg.generated
     */
    public Integer getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_supplier.region_id
     *
     * @param regionId the value for all_supplier.region_id
     *
     * @mbg.generated
     */
    public void setRegionId(Integer regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_supplier.supplier_name
     *
     * @return the value of all_supplier.supplier_name
     *
     * @mbg.generated
     */
    public String getSupplierName() {
        return supplierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_supplier.supplier_name
     *
     * @param supplierName the value for all_supplier.supplier_name
     *
     * @mbg.generated
     */
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_supplier.user_info_id
     *
     * @return the value of all_supplier.user_info_id
     *
     * @mbg.generated
     */
    public Integer getUserInfoId() {
        return userInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_supplier.user_info_id
     *
     * @param userInfoId the value for all_supplier.user_info_id
     *
     * @mbg.generated
     */
    public void setUserInfoId(Integer userInfoId) {
        this.userInfoId = userInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_supplier.contacts
     *
     * @return the value of all_supplier.contacts
     *
     * @mbg.generated
     */
    public String getContacts() {
        return contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_supplier.contacts
     *
     * @param contacts the value for all_supplier.contacts
     *
     * @mbg.generated
     */
    public void setContacts(String contacts) {
        this.contacts = contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_supplier.tel
     *
     * @return the value of all_supplier.tel
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_supplier.tel
     *
     * @param tel the value for all_supplier.tel
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_supplier.supplier_desc
     *
     * @return the value of all_supplier.supplier_desc
     *
     * @mbg.generated
     */
    public String getSupplierDesc() {
        return supplierDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_supplier.supplier_desc
     *
     * @param supplierDesc the value for all_supplier.supplier_desc
     *
     * @mbg.generated
     */
    public void setSupplierDesc(String supplierDesc) {
        this.supplierDesc = supplierDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_supplier.saleman
     *
     * @return the value of all_supplier.saleman
     *
     * @mbg.generated
     */
    public String getSaleman() {
        return saleman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_supplier.saleman
     *
     * @param saleman the value for all_supplier.saleman
     *
     * @mbg.generated
     */
    public void setSaleman(String saleman) {
        this.saleman = saleman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_supplier.supplier_add_man
     *
     * @return the value of all_supplier.supplier_add_man
     *
     * @mbg.generated
     */
    public String getSupplierAddMan() {
        return supplierAddMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_supplier.supplier_add_man
     *
     * @param supplierAddMan the value for all_supplier.supplier_add_man
     *
     * @mbg.generated
     */
    public void setSupplierAddMan(String supplierAddMan) {
        this.supplierAddMan = supplierAddMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_supplier.supplier_add_time
     *
     * @return the value of all_supplier.supplier_add_time
     *
     * @mbg.generated
     */
    public LocalDateTime getSupplierAddTime() {
        return supplierAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_supplier.supplier_add_time
     *
     * @param supplierAddTime the value for all_supplier.supplier_add_time
     *
     * @mbg.generated
     */
    public void setSupplierAddTime(LocalDateTime supplierAddTime) {
        this.supplierAddTime = supplierAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_supplier.supplier_last_modifier
     *
     * @return the value of all_supplier.supplier_last_modifier
     *
     * @mbg.generated
     */
    public String getSupplierLastModifier() {
        return supplierLastModifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_supplier.supplier_last_modifier
     *
     * @param supplierLastModifier the value for all_supplier.supplier_last_modifier
     *
     * @mbg.generated
     */
    public void setSupplierLastModifier(String supplierLastModifier) {
        this.supplierLastModifier = supplierLastModifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_supplier.supplier_last_edit_time
     *
     * @return the value of all_supplier.supplier_last_edit_time
     *
     * @mbg.generated
     */
    public LocalDateTime getSupplierLastEditTime() {
        return supplierLastEditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_supplier.supplier_last_edit_time
     *
     * @param supplierLastEditTime the value for all_supplier.supplier_last_edit_time
     *
     * @mbg.generated
     */
    public void setSupplierLastEditTime(LocalDateTime supplierLastEditTime) {
        this.supplierLastEditTime = supplierLastEditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_supplier
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", supplierId=").append(supplierId);
        sb.append(", regionId=").append(regionId);
        sb.append(", supplierName=").append(supplierName);
        sb.append(", userInfoId=").append(userInfoId);
        sb.append(", contacts=").append(contacts);
        sb.append(", tel=").append(tel);
        sb.append(", supplierDesc=").append(supplierDesc);
        sb.append(", saleman=").append(saleman);
        sb.append(", supplierAddMan=").append(supplierAddMan);
        sb.append(", supplierAddTime=").append(supplierAddTime);
        sb.append(", supplierLastModifier=").append(supplierLastModifier);
        sb.append(", supplierLastEditTime=").append(supplierLastEditTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_supplier
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AllSupplier other = (AllSupplier) that;
        return (this.getSupplierId() == null ? other.getSupplierId() == null : this.getSupplierId().equals(other.getSupplierId()))
            && (this.getRegionId() == null ? other.getRegionId() == null : this.getRegionId().equals(other.getRegionId()))
            && (this.getSupplierName() == null ? other.getSupplierName() == null : this.getSupplierName().equals(other.getSupplierName()))
            && (this.getUserInfoId() == null ? other.getUserInfoId() == null : this.getUserInfoId().equals(other.getUserInfoId()))
            && (this.getContacts() == null ? other.getContacts() == null : this.getContacts().equals(other.getContacts()))
            && (this.getTel() == null ? other.getTel() == null : this.getTel().equals(other.getTel()))
            && (this.getSupplierDesc() == null ? other.getSupplierDesc() == null : this.getSupplierDesc().equals(other.getSupplierDesc()))
            && (this.getSaleman() == null ? other.getSaleman() == null : this.getSaleman().equals(other.getSaleman()))
            && (this.getSupplierAddMan() == null ? other.getSupplierAddMan() == null : this.getSupplierAddMan().equals(other.getSupplierAddMan()))
            && (this.getSupplierAddTime() == null ? other.getSupplierAddTime() == null : this.getSupplierAddTime().equals(other.getSupplierAddTime()))
            && (this.getSupplierLastModifier() == null ? other.getSupplierLastModifier() == null : this.getSupplierLastModifier().equals(other.getSupplierLastModifier()))
            && (this.getSupplierLastEditTime() == null ? other.getSupplierLastEditTime() == null : this.getSupplierLastEditTime().equals(other.getSupplierLastEditTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table all_supplier
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSupplierId() == null) ? 0 : getSupplierId().hashCode());
        result = prime * result + ((getRegionId() == null) ? 0 : getRegionId().hashCode());
        result = prime * result + ((getSupplierName() == null) ? 0 : getSupplierName().hashCode());
        result = prime * result + ((getUserInfoId() == null) ? 0 : getUserInfoId().hashCode());
        result = prime * result + ((getContacts() == null) ? 0 : getContacts().hashCode());
        result = prime * result + ((getTel() == null) ? 0 : getTel().hashCode());
        result = prime * result + ((getSupplierDesc() == null) ? 0 : getSupplierDesc().hashCode());
        result = prime * result + ((getSaleman() == null) ? 0 : getSaleman().hashCode());
        result = prime * result + ((getSupplierAddMan() == null) ? 0 : getSupplierAddMan().hashCode());
        result = prime * result + ((getSupplierAddTime() == null) ? 0 : getSupplierAddTime().hashCode());
        result = prime * result + ((getSupplierLastModifier() == null) ? 0 : getSupplierLastModifier().hashCode());
        result = prime * result + ((getSupplierLastEditTime() == null) ? 0 : getSupplierLastEditTime().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table all_supplier
     *
     * @mbg.generated
     */
    public enum Column {
        supplierId("supplier_id", "supplierId", "INTEGER", false),
        regionId("region_id", "regionId", "INTEGER", false),
        supplierName("supplier_name", "supplierName", "VARCHAR", false),
        userInfoId("user_info_id", "userInfoId", "INTEGER", false),
        contacts("contacts", "contacts", "VARCHAR", false),
        tel("tel", "tel", "VARCHAR", false),
        supplierDesc("supplier_desc", "supplierDesc", "VARCHAR", false),
        saleman("saleman", "saleman", "VARCHAR", false),
        supplierAddMan("supplier_add_man", "supplierAddMan", "VARCHAR", false),
        supplierAddTime("supplier_add_time", "supplierAddTime", "TIMESTAMP", false),
        supplierLastModifier("supplier_last_modifier", "supplierLastModifier", "VARCHAR", false),
        supplierLastEditTime("supplier_last_edit_time", "supplierLastEditTime", "TIMESTAMP", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table all_supplier
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table all_supplier
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table all_supplier
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table all_supplier
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table all_supplier
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table all_supplier
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_supplier
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_supplier
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_supplier
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_supplier
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_supplier
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_supplier
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_supplier
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_supplier
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_supplier
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table all_supplier
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}